<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-GVHCX64" failures="5" tests="6" name="API Tests" time="2.756" errors="0" timestamp="2025-09-03T22:35:33 IST">
  <testcase classname="com.api.tests.AccountCreationTest" name="accountCreationTestViaJsonPayload" time="2.41">
    <failure type="java.lang.AssertionError" message="Status code is not matching expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Status code is not matching expected [200] but found [400]
at com.api.tests.AccountCreationTest.accountCreationTestViaJsonPayload(AccountCreationTest.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- accountCreationTestViaJsonPayload -->
  <testcase classname="com.api.tests.AccountCreationTest" name="accountCreationTestViaJsonPayloadViaPaths" time="2.412">
    <failure type="java.lang.AssertionError" message="Status code is not matching expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Status code is not matching expected [200] but found [400]
at com.api.tests.AccountCreationTest.accountCreationTestViaJsonPayloadViaPaths(AccountCreationTest.java:76)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- accountCreationTestViaJsonPayloadViaPaths -->
  <testcase classname="com.api.tests.AccountCreationTest" name="accountCreationTestViaTestNGDataProvider" time="0.122">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at com.api.tests.AccountCreationTest.accountCreationTestViaTestNGDataProvider(AccountCreationTest.java:63)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- accountCreationTestViaTestNGDataProvider -->
  <testcase classname="com.api.tests.AccountCreationTest" name="accountCreationTest" time="2.602"/>
  <testcase classname="com.api.tests.AccountCreationTest" name="validSignupTest" time="0.081">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at com.api.tests.AccountCreationTest.validSignupTest(AccountCreationTest.java:83)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validSignupTest -->
  <testcase classname="com.api.tests.AccountCreationTest" name="duplicateEmailTest" time="0.223">
    <failure type="java.lang.AssertionError" message="expected [409] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [409] but found [400]
at com.api.tests.AccountCreationTest.duplicateEmailTest(AccountCreationTest.java:90)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- duplicateEmailTest -->
</testsuite> <!-- API Tests -->
